data:
  seed: 42

checkpoint:
  path: "trained_models/whisper_frontend_mesonet/ckpt.pth"

model:
  name: "whisper_frontend_mesonet"
  parameters:
    freeze_encoder: false
    input_channels: 2
    fc1_dim: 1024
    frontend_algorithm: ["lfcc"]
  optimizer:
    lr: 1.0e-06
    weight_decay: 0.0001