data:
  seed: 42

checkpoint:
  path: ""

model:
  name: "whisper_frontend_mesonet"
  parameters:
    freeze_encoder: True
    input_channels: 2
    fc1_dim: 1024
    frontend_algorithm: ["mfcc"]
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001

