data:
  seed: 42

checkpoint:
  path: ""

model:
  name: "whisper_mesonet"
  parameters:
    freeze_encoder: True
    input_channels: 1
    fc1_dim: 1024
    frontend_algorithm: []
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
